import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// ─── Helper : save notification into IndexedDB from Service Worker ───────────
const DB_NAME = 'HariClubDB';
const DB_VERSION = 2;

function openDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = (e) => {
      const db = e.target.result;
      if (!db.objectStoreNames.contains('cache')) {
        db.createObjectStore('cache', { keyPath: 'key' });
      }
      if (!db.objectStoreNames.contains('notifications')) {
        db.createObjectStore('notifications', { keyPath: 'id' });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror  = () => reject(req.error);
  });
}

async function saveNotifToDB(notif) {
  try {
    const db = await openDB();
    const tx = db.transaction('notifications', 'readwrite');
    tx.objectStore('notifications').put(notif);
    await new Promise((res, rej) => { tx.oncomplete = res; tx.onerror = rej; });
  } catch (e) {
    console.warn('[SW] IndexedDB save failed:', e);
  }
}

// ─── Handle incoming Push Notifications ─────────────────────────────────────
self.addEventListener('push', (event) => {
  let data = { title: 'Hari Club Hotel', body: 'Nouvelle notification' };

  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    icon: '/favicon.svg',
    badge: '/favicon.svg',
    vibrate: [100, 50, 100],
    data: { url: data.url || '/client/notifications' }
  };

  // Build the notification object identical to what the Socket emits
  const notifRecord = {
    id: Date.now(),
    title: data.title || 'Hari Club Hotel',
    message: data.body,
    type: 'MARKETING',
    refId: null,
    refType: data.url || '/client/notifications',
    time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    timestamp: Date.now(),
    read: false
  };

  event.waitUntil(
    Promise.all([
      // 1. Show the OS notification banner
      self.registration.showNotification(data.title, options),

      // 2. Persist in IndexedDB so the centre de notifications can read it
      saveNotifToDB(notifRecord),

      // 3. Notify any open React tabs so they update their state immediately
      clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
        windowClients.forEach((client) => {
          client.postMessage({ type: 'PUSH_NOTIF', notif: notifRecord });
        });
      })
    ])
  );
});

// ─── Open / focus the right URL when the notification banner is clicked ───────
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const urlToOpen = new URL(event.notification.data.url || '/', self.location.origin).href;

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
